services:
  # Backend API only
  - type: web
    name: cares-services-backend
    env: node
    plan: free
    buildCommand: cd Back && npm install
    startCommand: cd Back && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: N8N_WEBHOOK_URL
        sync: false
    healthCheckPath: /products
    autoDeploy: true
    branch: main
